/**
 * QC Read API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountDetails model module.
 * @module model/AccountDetails
 * @version v1
 */
class AccountDetails {
    /**
     * Constructs a new <code>AccountDetails</code>.
     * @alias module:model/AccountDetails
     */
    constructor() { 
        
        AccountDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountDetails} obj Optional instance to populate.
     * @return {module:model/AccountDetails} The populated <code>AccountDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountDetails();

            if (data.hasOwnProperty('balance')) {
                obj['balance'] = ApiClient.convertToType(data['balance'], 'String');
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'Number');
            }
            if (data.hasOwnProperty('blockNumber')) {
                obj['blockNumber'] = ApiClient.convertToType(data['blockNumber'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AccountDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AccountDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['balance'] && !(typeof data['balance'] === 'string' || data['balance'] instanceof String)) {
            throw new Error("Expected the field `balance` to be a primitive type in the JSON string but got " + data['balance']);
        }

        return true;
    }


}



/**
 * @member {String} balance
 */
AccountDetails.prototype['balance'] = undefined;

/**
 * @member {Number} nonce
 */
AccountDetails.prototype['nonce'] = undefined;

/**
 * The block number as of which the details were retrieved
 * @member {Number} blockNumber
 */
AccountDetails.prototype['blockNumber'] = undefined;






export default AccountDetails;

