/**
 * QC Read API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QcReadApi);
  }
}(this, function(expect, QcReadApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QcReadApi.Balance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Balance', function() {
    it('should create an instance of Balance', function() {
      // uncomment below and update the code to test Balance
      //var instance = new QcReadApi.Balance();
      //expect(instance).to.be.a(QcReadApi.Balance);
    });

    it('should have the property balance (base name: "balance")', function() {
      // uncomment below and update the code to test the property balance
      //var instance = new QcReadApi.Balance();
      //expect(instance).to.be();
    });

    it('should have the property nonce (base name: "nonce")', function() {
      // uncomment below and update the code to test the property nonce
      //var instance = new QcReadApi.Balance();
      //expect(instance).to.be();
    });

    it('should have the property blockNumber (base name: "blockNumber")', function() {
      // uncomment below and update the code to test the property blockNumber
      //var instance = new QcReadApi.Balance();
      //expect(instance).to.be();
    });

    it('should have the property blockDate (base name: "blockDate")', function() {
      // uncomment below and update the code to test the property blockDate
      //var instance = new QcReadApi.Balance();
      //expect(instance).to.be();
    });

  });

}));
