/**
 * QC Read API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QcReadApi);
  }
}(this, function(expect, QcReadApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QcReadApi.TransactionReceipt();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionReceipt', function() {
    it('should create an instance of TransactionReceipt', function() {
      // uncomment below and update the code to test TransactionReceipt
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be.a(QcReadApi.TransactionReceipt);
    });

    it('should have the property cumulativeGasUsed (base name: "cumulativeGasUsed")', function() {
      // uncomment below and update the code to test the property cumulativeGasUsed
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property effectiveGasPrice (base name: "effectiveGasPrice")', function() {
      // uncomment below and update the code to test the property effectiveGasPrice
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property gasUsed (base name: "gasUsed")', function() {
      // uncomment below and update the code to test the property gasUsed
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property hash (base name: "hash")', function() {
      // uncomment below and update the code to test the property hash
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new QcReadApi.TransactionReceipt();
      //expect(instance).to.be();
    });

  });

}));
